# ----------------------------------------------------------------------------
# RTL VHDL output 'rtl.vhdl' vs Untimed C++
#
#    HLS version: 2011a.200 Production Release
#       HLS date: Mon Jun  2 22:10:04 PDT 2014
#  Flow Packages: HDL_Tcl 2008a.1, SCVerify 2009a.1
#
#   Generated by: xph3sle512@cimeld21
# Generated date: Wed Feb 01 14:06:25 CET 2017
#
# ----------------------------------------------------------------------------
# ===================================================
# DEFAULT GOAL is the help target
.PHONY: all
all: help

# ===================================================
# VARIABLES
# 
MGC_HOME          = /softslin/catapult2011a_200_12/Mgc_home/
PROJDIR           = $(subst /,$(PATHSEP),../..)
SOLNDIR           = $(subst /,$(PATHSEP),Catapult_1/Main_Only_Comp_Decomp__Main_Fonction.v1)
export MGC_HOME

# Variables that can be overridden from the make command line
ifeq "$(INCL_DIRS)" ""
INCL_DIRS                   = ./scverify . ../.. /usr/x86_64-linux-gnu
endif
export INCL_DIRS
ifeq "$(STAGE)" ""
STAGE                       = rtl
endif
export STAGE
ifeq "$(SIMTOOL)" ""
SIMTOOL                     = msim
endif
export SIMTOOL
ifeq "$(NETLIST)" ""
NETLIST                     = vhdl
endif
export NETLIST
ifeq "$(RTL_NETLIST_FNAME)" ""
RTL_NETLIST_FNAME           = /tp/xph3sle/xph3sle512/ProjetSLE_bis/dataCatapultC/Catapult_1/Main_Only_Comp_Decomp__Main_Fonction.v1/rtl.vhdl
endif
export RTL_NETLIST_FNAME
ifeq "$(TARGET)" ""
TARGET                      = scverify/$(STAGE)_$(NETLIST)_$(SIMTOOL)
endif
export TARGET
ifeq "$(INVOKE_ARGS)" ""
INVOKE_ARGS                 = 
endif
export INVOKE_ARGS
export SCVLIBS
export MODELSIM
TOP_HDL_ENTITY           += Main_Only_Comp_Decomp_Main_Fonction
TOP_DU                   += scverify_top
CXX_TYPE                 += gcc
MSIM_SCRIPT              += ./Catapult_1/Main_Only_Comp_Decomp__Main_Fonction.v1/scverify_msim.tcl

ifeq ($(RECUR),)
ifeq ($(STAGE),mapped)
ifeq ($(RTLTOOL),)
   $(error This makefile requires specifying the RTLTOOL variable on the make command line)
endif
endif
endif
# ===================================================
# Include makefile for default commands and variables
include $(MGC_HOME)/shared/include/mkfiles/ccs_default_cmds.mk

# ===================================================
# Include environment variables set by flow options
include ./ccs_env.mk

# ===================================================
# SOURCES
# 
# Specify list of Modelsim libraries to create
HDL_LIB_NAMES = mgc_hls work
# Specify list of source files - MUST be ordered properly
ifeq ($(STAGE),gate)
ifeq ($(RTLTOOL),)
ifeq ($(GATE_VHDL_DEP),)
GATE_VHDL_DEP = ./rtl.vhdl/rtl.vhdl.vhdlts
endif
ifeq ($(GATE_VLOG_DEP),)
GATE_VLOG_DEP = 
endif
endif
VHDL_SRC = ./rtl_funcs.vhd/rtl_funcs.vhd.vhdlts ./rtl_mux_pkg.vhdl/rtl_mux_pkg.vhdl.vhdlts ./rtl_mgc_ioport.vhd/rtl_mgc_ioport.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_comps.vhd/mgc_comps.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_generic_reg_beh.vhd/mgc_generic_reg_beh.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ram_singleport_be_fpga.vhd/ram_singleport_be_fpga.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_div_beh.vhd/mgc_div_beh.vhd.vhdlts $(GATE_VHDL_DEP)
VLOG_SRC =  $(GATE_VLOG_DEP)
else
VHDL_SRC = ./rtl_funcs.vhd/rtl_funcs.vhd.vhdlts ./rtl_mux_pkg.vhdl/rtl_mux_pkg.vhdl.vhdlts ./rtl_mgc_ioport.vhd/rtl_mgc_ioport.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_comps.vhd/mgc_comps.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_generic_reg_beh.vhd/mgc_generic_reg_beh.vhd.vhdlts $(MGC_HOME)/pkgs/siflibs/ram_singleport_be_fpga.vhd/ram_singleport_be_fpga.vhd.vhdlts $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_div_beh.vhd/mgc_div_beh.vhd.vhdlts ./rtl.vhdl/rtl.vhdl.vhdlts
VLOG_SRC = 
endif
CXX_SRC  = ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Decomp.cpp/Main_Decomp.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Exchange.cpp/Exchange.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/model.cpp/model.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Decompressor.cpp/Decompressor.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Cod_Entropique.cpp/Main_Cod_Entropique.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Only_Comp_Decomp.cpp/Main_Only_Comp_Decomp.cpp.cxxts ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Compressor.cpp/Compressor.cpp.cxxts ./scverify/mc_testbench.cpp/mc_testbench.cpp.cxxts ./scverify/scverify_top.cpp/scverify_top.cpp.cxxts
# Specify RTL synthesis scripts (if any)
RTL_SCRIPT = 

# Specify hold time file name (for verifying synthesized netlists)
HLD_CONSTRAINT_FNAME = top_gate_constraints.cpp

# ===================================================
# GLOBAL OPTIONS
# 
# CXXFLAGS - global C++ options (apply to all C++ compilations) except for include file search paths
CXXFLAGS += -DCCS_SCVERIFY -DSC_INCLUDE_DYNAMIC_PROCESSES -DSC_USE_STD_STRING -DSC_INCLUDE_MTI_AC -DTOP_HDL_ENTITY=$(TOP_HDL_ENTITY) -DCCS_MISMATCHED_OUTPUTS_ONLY -Wall
# 
# If the make command line includes a definition of the special variable MC_DEFAULT_TRANSACTOR_LOG
# then define that value for all compilations as well
ifneq "$(MC_DEFAULT_TRANSACTOR_LOG)" ""
CXXFLAGS += -DMC_DEFAULT_TRANSACTOR_LOG=$(MC_DEFAULT_TRANSACTOR_LOG)
endif
# 
# CXX_INCLUDES - include file search paths
CXX_INCLUDES = ./scverify . ../.. /usr/x86_64-linux-gnu
# 
# TCL shell
TCLSH_CMD = $(MGC_HOME)/bin/tclsh8.5

# Pass along SCVerify_DEADLOCK_DETECTION option
ifneq "$(SCVerify_DEADLOCK_DETECTION)" ""
CXXFLAGS += -DDEADLOCK_DETECTION
endif
# ===================================================
# PER SOURCE FILE SPECIALIZATIONS
# 
# Specify source file paths
$(TARGET)/rtl_funcs.vhd.vhdlts: ./rtl_funcs.vhd
$(TARGET)/rtl_mux_pkg.vhdl.vhdlts: ./rtl_mux_pkg.vhdl
$(TARGET)/rtl_mgc_ioport.vhd.vhdlts: ./rtl_mgc_ioport.vhd
$(TARGET)/mgc_comps.vhd.vhdlts: $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_comps.vhd
$(TARGET)/mgc_generic_reg_beh.vhd.vhdlts: $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_generic_reg_beh.vhd
$(TARGET)/ram_singleport_be_fpga.vhd.vhdlts: $(MGC_HOME)/pkgs/siflibs/ram_singleport_be_fpga.vhd
$(TARGET)/mgc_div_beh.vhd.vhdlts: $(MGC_HOME)/pkgs/hls_pkgs/mgc_comps_src/mgc_div_beh.vhd
$(TARGET)/rtl.vhdl.vhdlts: ./rtl.vhdl
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): $(dir $(GATE_VHDL_DEP))
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): $(dir $(GATE_VLOG_DEP))
endif
endif
$(TARGET)/Main_Decomp.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Decomp.cpp
$(TARGET)/Exchange.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Exchange.cpp
$(TARGET)/model.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/model.cpp
$(TARGET)/Decompressor.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Decompressor.cpp
$(TARGET)/Main_Cod_Entropique.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Cod_Entropique.cpp
$(TARGET)/Main_Only_Comp_Decomp.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Main_Only_Comp_Decomp.cpp
$(TARGET)/Compressor.cpp.cxxts: ../../../Rendu/src/CPP_for_Catapult/comp_decomp_noW/Compressor.cpp
$(TARGET)/mc_testbench.cpp.cxxts: ./scverify/mc_testbench.cpp
$(TARGET)/scverify_top.cpp.cxxts: ./scverify/scverify_top.cpp
# 
# Specify additional C++ options per C++ source by setting CXX_OPTS
$(TARGET)/Compressor.cpp.cxxts: CXX_OPTS=
$(TARGET)/Main_Only_Comp_Decomp.cpp.cxxts: CXX_OPTS=
$(TARGET)/Main_Cod_Entropique.cpp.cxxts: CXX_OPTS=
$(TARGET)/model.cpp.cxxts: CXX_OPTS=
$(TARGET)/Exchange.cpp.cxxts: CXX_OPTS=
$(TARGET)/scverify_top.cpp.cxxts: CXX_OPTS=
$(TARGET)/mc_testbench.cpp.cxxts: CXX_OPTS=
$(TARGET)/Decompressor.cpp.cxxts: CXX_OPTS=
$(TARGET)/Main_Decomp.cpp.cxxts: CXX_OPTS=
# 
# Specify dependencies
$(TARGET)/Main_Decomp.cpp.cxxts: 
$(TARGET)/Exchange.cpp.cxxts: 
$(TARGET)/model.cpp.cxxts: 
$(TARGET)/Decompressor.cpp.cxxts: 
$(TARGET)/Main_Cod_Entropique.cpp.cxxts: 
$(TARGET)/Main_Only_Comp_Decomp.cpp.cxxts: 
$(TARGET)/Compressor.cpp.cxxts: 
$(TARGET)/mc_testbench.cpp.cxxts: 
$(TARGET)/scverify_top.cpp.cxxts: 
# 
# Specify compilation library for HDL source
$(TARGET)/mgc_generic_reg_beh.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/mgc_comps.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/ram_singleport_be_fpga.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/rtl.vhdl.vhdlts: HDL_LIB=work
$(TARGET)/mgc_div_beh.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/rtl_mgc_ioport.vhd.vhdlts: HDL_LIB=mgc_hls
$(TARGET)/rtl_mux_pkg.vhdl.vhdlts: HDL_LIB=work
$(TARGET)/rtl_funcs.vhd.vhdlts: HDL_LIB=mgc_hls
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): HDL_LIB=work
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): HDL_LIB=work
endif
endif
# 
# Specify top design unit for HDL source
$(TARGET)/rtl.vhdl.vhdlts: DUT_E=Main_Only_Comp_Decomp_Main_Fonction
$(TARGET)/rtl_mux_pkg.vhdl.vhdlts: DUT_E=Main_Only_Comp_Decomp_Main_Fonction_mux_pkg

# Specify top design unit
$(TARGET)/rtl.vhdl.vhdlts: VHDL_TOP=1

ifneq "$(RTLTOOL)" ""
# ===================================================
# Include makefile for RTL synthesis
include $(MGC_HOME)/shared/include/mkfiles/ccs_$(RTLTOOL).mk
else
# ===================================================
# Include makefile for simulator
include $(MGC_HOME)/shared/include/mkfiles/ccs_$(SIMTOOL).mk
endif

