directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,17,0,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,17,0,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,17,0,17)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,17,0,17)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/cmodel.reset:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/cmodel.reset#2:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#50 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#50 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::getChar:for:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#49 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:for:i:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#13 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,8,0,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,8,0,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,8,0,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(16,0,8,0,16)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#13 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(16,0,8,0,16)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#2:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#8:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#6:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#44 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#1:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#72 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#72 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#5:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#11:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#1:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#7:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#1:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#7:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#63 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#63 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#6:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#64 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#64 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#5:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#11:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#46 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#46 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#52 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#52 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#3
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#30 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#3
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#8:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#3
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.moy#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#3
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#30 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#4
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#4
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.getByte:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#1:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#3:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#5:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#7:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.m_input.get_bit:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.m_input.get_bit#1:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.m_output.putByte:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/main_decomp.Mn_Fonction:for:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,2,1,17)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(15,0,1,1,16)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(15,0,1,1,16)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:acc RESOURCE_NAME ModelA:mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,15,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update#1:acc RESOURCE_NAME ModelA:mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,15,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,16,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,16,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:range:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,16,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:range:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,16,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,32,0,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,32,0,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for:if:if#1:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:if#2:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:for:else:else:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#1:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#2:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#3:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_x#2:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#2:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update#1:for:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for:if:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:if#2:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:for:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update#1:for:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,0,2,1,32)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::getChar:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#65 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#65 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#70 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#66 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#70 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#66 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#68 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#68 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#69 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#69 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:if#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending:for:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#2:for:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#10 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_x#2:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#2:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#3 RESOURCE_NAME inv_wave.Mn_Inv_Wave_Fct:for#1:mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:if#2:acc#1 RESOURCE_NAME inv_wave.Mn_Inv_Wave_Fct:for#1:mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,2,1,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x#1:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_x:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_x:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#42 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#76 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#76 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#75 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#75 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:mul RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_mul(32,0,32,0,64)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:mul#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_mul(32,0,32,0,64)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:scaled_value:mul RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_mul(32,0,34,1,66)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:mul#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_mul(32,0,34,1,66)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:mul RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_mul(32,0,34,1,66)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_x:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#43 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#67 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#67 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:for:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_x:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_x#1:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#51 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_x#1:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.getByte:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.m_output.putByte:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#74 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#59 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/main_decomp.Mn_Fonction:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#46 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#59 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#52 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#45 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#44 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,6,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y#1:acc#49 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,6,0,8)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#2:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#1:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#8:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#7:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#5:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#11:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/passe_y:acc#48 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/trans_ond.sub#6:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:range:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(15,0,2,1,15)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:range:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(15,0,2,1,15)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:for:else:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,1,1,18)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:for:else:if:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,1,1,18)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:for:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,1,1,18)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:for:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(17,0,1,1,18)#1
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#9 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/ModelA::update#1:for:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x#1:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#51 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#51 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(31,0,9,1,31)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/dec.decompress:for#1:for:else:else:if:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(18,0,3,1,19)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.compress:for:for:else:else:if:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(18,0,3,1,19)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/inv_wave.Mn_Inv_Wave_Fct:for#1:acc#11 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_x#2:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#1:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#3:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.put_bit_plus_pending#2:for:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#2:acc#9 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(33,1,33,1,34)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#73 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#73 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,9)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(11,0,11,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(11,0,11,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/copy_y#2:acc#6 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(11,0,11,0,11)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#58 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(3,0,3,0,4)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#58 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(3,0,3,0,4)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(22,0,8,1,23)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#5:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(22,0,8,1,23)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#7:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(22,0,8,1,23)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#1:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(22,0,8,1,23)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/comp.m_output.putByte#3:if:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(22,0,8,1,23)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,9,0,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_x#1:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,9,0,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y:acc#57 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,10,0,33)
directive set /Main_Comp_Decomp_tot::Main_Fonction/Main_Comp_Decomp_tot::Main_Fonction:core/WAIT_DP#1/hsplit_y#1:acc#57 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(32,1,10,0,33)
